#!/usr/bin/env bash
# verified-commits gate.
# Every commit in the range under review must (1) carry a signature the PLATFORM marks as verified
# (the GitHub/GitLab "Verified" badge — proves the commit was signed by a key registered to the
# account that owns the author email) and (2) be AUTHORED by a known identity: the author email must
# appear in the .sdlc/verified-authors allowlist (generated by `yad check --fix` from the hub
# roster's `email` fields + hub.json `verified_authors`). Unsigned commits and commits from unknown
# authors do not reach merge — on the product hub and on every connected repo alike.
#
# Only the AUTHOR email is checked against the allowlist: platform-generated merge/squash/update
# commits set the platform itself as the committer (e.g. noreply@github.com), and their integrity is
# covered by the signature check (the platform signs them).
#
# Merge-commit signature exemption: a merge that introduces NO content of its own (its combined diff
# is empty — no conflict-resolution / evil-merge hunks) is signature-waived, because every change it
# carries already lives in its individually author+signature-checked parents. This unblocks self-hosted
# GitLab, which does not sign UI-created merge commits (the signature API returns 404). A merge that
# DOES introduce content of its own still requires a verified signature (fail-closed).
#
# Degradation is explicit, never silent:
#   - no allowlist file        -> author check SKIPPED with a warning (configure emails, re-wire)
#   - no GitHub/GitLab remote  -> signature check SKIPPED with a warning (no platform, no badge)
#   - platform API unreachable -> FAIL closed (a security gate must not pass on a broken check)
#
# GitLab note: the signature API is not readable with CI_JOB_TOKEN — provide a CI variable
# GITLAB_TOKEN (or SDLC_API_TOKEN) with read_api scope; see the pipeline fragment header.
set -euo pipefail

BASE="${1:-${SDLC_BASE:-origin/main}}"

# Fail closed if the base ref can't be resolved (shallow clone / wrong base branch / unfetched ref).
if ! git rev-parse --verify --quiet "${BASE}^{commit}" >/dev/null; then
  echo "FAIL [verified-commits]: base ref '${BASE}' not found — fetch full history / check the base branch."
  exit 1
fi
RANGE="${BASE}..HEAD"

commits="$(git rev-list "$RANGE")"
if [ -z "$commits" ]; then
  echo "PASS [verified-commits]: no commits in ${RANGE}"
  exit 0
fi

# ---- author allowlist (one email per line; # comments; case-insensitive) -------------------------
ALLOWLIST="${SDLC_VERIFIED_AUTHORS:-.sdlc/verified-authors}"
authors_on=0
if [ -f "$ALLOWLIST" ]; then
  authors_on=1
else
  echo "WARN [verified-commits]: ${ALLOWLIST} not found — author allowlist NOT enforced. Add 'email' to the hub roster (or hub.json 'verified_authors'), then run \`yad check --fix\`."
fi

# ---- platform for the signature check (override with SDLC_PLATFORM=github|gitlab|none) -----------
remote="$(git remote get-url origin 2>/dev/null || true)"
platform=""
case "$remote" in
  *github*) platform=github ;;
  *gitlab*) platform=gitlab ;;
esac
platform="${SDLC_PLATFORM:-$platform}"
case "$platform" in
  github|gitlab) ;;
  ""|none)
    platform=""
    echo "WARN [verified-commits]: no GitHub/GitLab remote — signature verification SKIPPED (the Verified badge is a platform concept)."
    ;;
  *)
    # Fail closed: an unknown override must never let signature checks silently pass.
    echo "FAIL [verified-commits]: unknown platform '${platform}' (SDLC_PLATFORM must be github|gitlab|none)."
    exit 1
    ;;
esac

# 0 when the platform marks the commit's signature verified.
signature_verified() {
  local sha v body
  sha="$1"
  case "$platform" in
    github)
      v="$(gh api "repos/{owner}/{repo}/commits/${sha}" --jq '.commit.verification.verified' 2>/dev/null || echo api-error)"
      [ "$v" = "true" ]
      ;;
    gitlab)
      # In CI use the documented API directly; locally fall back to the user's own glab.
      if [ -n "${CI_API_V4_URL:-}" ] && [ -n "${CI_PROJECT_ID:-}" ]; then
        body="$(curl -fsS --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-${SDLC_API_TOKEN:-}}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/commits/${sha}/signature" 2>/dev/null || true)"
      else
        body="$(glab api "projects/:id/repository/commits/${sha}/signature" 2>/dev/null || true)"
      fi
      printf '%s' "$body" | grep -qE '"verification_status"[[:space:]]*:[[:space:]]*"verified"'
      ;;
    *) return 1 ;; # unreachable (platform validated above) — keep the gate fail-closed regardless
  esac
}

# 0 when a merge commit introduced NO content of its own. The combined diff (--cc) lists only hunks
# that differ from ALL parents, so empty output means every change lives in an individually-checked
# parent — there is no conflict-resolution or evil-merge content unique to the merge commit, hence
# nothing an unverified author could smuggle in past the per-parent author+signature checks.
merge_introduces_no_content() {
  # `local` on its own line: `local out=$(...)` would mask the substitution's exit status (local
  # always returns 0). A git error (e.g. a parent tree missing in a shallow clone) must fail closed —
  # an empty stdout from a *failed* command is not evidence the merge is content-free.
  local out
  out="$(git diff-tree --cc --no-commit-id -r "$1")" || return 1
  [ -z "$out" ]
}

rc=0
while IFS= read -r sha; do
  [ -z "$sha" ] && continue
  short="$(git log -1 --format=%h "$sha")"
  author="$(git log -1 --format=%ae "$sha" | tr '[:upper:]' '[:lower:]')"
  # The gate-sync bot is a machine identity, not a roster human — waive the allowlist for it. Its
  # commits are still held to the SIGNATURE check below, so a contributor cannot spoof the bot author
  # to dodge the allowlist (a forged-author commit is not platform-Verified). Mirrors how the
  # platform-committer merge commits are allowlist-exempt but signature-covered.
  is_bot=0
  case "${author}|$(git log -1 --format=%an "$sha" | tr '[:upper:]' '[:lower:]')" in *yad-gate-sync*) is_bot=1 ;; esac

  # A merge commit (2+ parents) is authored by whoever pressed "merge" — often a platform noreply
  # address, not a roster human — while its CONTENT already passed the PR gate suite. Waive the
  # allowlist for it (like the bot), but STILL require the signature below: a platform merge commit is
  # Verified, so a locally-forged merge pushed direct-to-default cannot dodge the check. This matters
  # for the push-on-default yad-update-guard, which (unlike the PR-triggered gates) sees merge commits.
  is_merge=0
  [ "$(git log -1 --format=%P "$sha" | wc -w | tr -d '[:space:]')" -ge 2 ] && is_merge=1

  if [ "$authors_on" = 1 ] && [ "$is_bot" = 0 ] && [ "$is_merge" = 0 ]; then
    # tolerate CRLF / stray surrounding whitespace in a hand-edited allowlist
    if grep -vE '^[[:space:]]*(#|$)' "$ALLOWLIST" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
        | tr '[:upper:]' '[:lower:]' | grep -qxF "$author"; then
      echo "PASS [verified-commits]: ${short} author <${author}> is a known identity"
    else
      echo "FAIL [verified-commits]: ${short} author <${author}> is not in ${ALLOWLIST} — unverified user."
      rc=1
    fi
  elif [ "$is_bot" = 1 ]; then
    echo "PASS [verified-commits]: ${short} gate-sync bot — allowlist waived (signature still required)"
  elif [ "$is_merge" = 1 ]; then
    echo "PASS [verified-commits]: ${short} merge commit — allowlist waived (signature still required)"
  fi

  if [ -n "$platform" ]; then
    if signature_verified "$sha"; then
      echo "PASS [verified-commits]: ${short} signature verified by ${platform}"
    elif [ "$is_merge" = 1 ] && merge_introduces_no_content "$sha"; then
      # Content-free merge: nothing to protect. Self-hosted GitLab does not sign UI merge commits, so
      # requiring a signature here would block every routine merge. An evil merge (content of its own)
      # falls through to FAIL below.
      echo "WARN [verified-commits]: ${short} unsigned merge commit — introduces no content of its own (covered by verified parents); signature waived. (Self-hosted GitLab does not sign UI merge commits; on a platform that signs its merges an unsigned content-free merge is unusual but still harmless.)"
    else
      echo "FAIL [verified-commits]: ${short} signature missing/unverified — sign commits (GPG/SSH key registered on ${platform}), or the signature API was unreachable (GitLab: set GITLAB_TOKEN/SDLC_API_TOKEN with read_api)."
      rc=1
    fi
  fi
done <<EOF
$commits
EOF

exit "$rc"
