// `yad docs list|build|deploy|sync` — the build/deploy/staleness mechanics for the interactive
// documentation sites generated by the yad-docs / yad-docs-overview skills. The CONTENT generation
// (reading epic/architecture/contract/ui/stories → writing src/data/*.ts and theming index.css) is
// the AI step inside those skills; this module only does the mechanical parts: npm build (a
// subprocess, like yad-spec shelling npx repomix), the platform Pages wiring (reusing platform.mjs),
// and the manifest-hash staleness check (reusing the head-sha idea from repo.mjs). It NEVER touches
// epic state, approvals, or the contract lock — docs are an output enrichment, not a gate.
//
// Pure mapping fns (deployTargetFromHub / siteBasePath / docsArtifactHash / docsStale / pagesWorkflow)
// are exported for unit tests; the side-effecting runDocs orchestrates them.
import path from 'node:path';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { c, log, ok, info, warn, hand, fail, readJSON, run, has, exists } from './lib.mjs';
import { PROJECT_FILES, VERSION } from './manifest.mjs';
import { detectPlatform, platformReady } from './platform.mjs';
import { gitHead } from './setup.mjs';
import { contractSurfaceHash } from './epic-state.mjs';

// ---- registry + site locations ------------------------------------------------------------------
function loadDocs(root) {
  const regPath = path.join(root, PROJECT_FILES.docsConfig);
  return { regPath, docs: readJSON(regPath, null) };
}

// Per-epic site lives beside the epic artifacts; the overview is project-level under docs/.
export function siteDir(root, { epic, overview } = {}) {
  if (overview) return path.join(root, 'docs/sdlc-site');
  return path.join(root, 'epics', epic, 'docs-site');
}
export function manifestPath(root, { epic, overview } = {}) {
  if (overview) return path.join(siteDir(root, { overview }), '.docs-build.json');
  return path.join(root, 'epics', epic, '.sdlc/docs-build.json');
}

// ---- pure: platform/target + base path ----------------------------------------------------------
// hub.json platform -> the default Pages target (github-pages | gitlab-pages | none/build-only).
export function deployTargetFromHub(hub = {}) {
  const platform = hub?.platform || detectPlatform(hub?.git_url || '');
  if (platform === 'github') return 'github-pages';
  if (platform === 'gitlab') return 'gitlab-pages';
  return 'none';
}

// The Vite `base` for one site: join the project base path (from docs.json) with the per-site
// subpath. The overview SPA mounts under `app/` so the hand-maintained report.html can own the
// Pages root (`<base>/`) as the main documentation; per-epic sites nest under epics/<id>/. Always a
// leading+trailing slash so it works as a Vite base and a router basename.
export function siteBasePath(docs = {}, { epic, overview } = {}) {
  const root = (docs.basePath || '/').replace(/\/+$/, '') || '';
  const sub = overview ? '/app' : epic ? `/epics/${epic}` : '';
  const joined = `${root}${sub}`.replace(/\/+/g, '/');
  return joined ? `${joined.replace(/\/$/, '')}/` : '/';
}

// ---- pure: staleness ----------------------------------------------------------------------------
// The artifacts whose content a per-epic site is generated from (any that exist contribute).
// contract.md is deliberately EXCLUDED here: it is folded in via its CONTRACT-SURFACE block hash
// (docsArtifactHash's `extra`), so docs-staleness tracks the same locked surface as the contract
// lock — non-surface prose edits to contract.md don't needlessly mark the docs stale.
export function docsArtifactFiles(root, epic) {
  const epicRoot = path.join(root, 'epics', epic);
  const flat = ['epic.md', 'architecture.md', 'ui-design.md', 'DESIGN.md', 'test-cases.md']
    .map((f) => path.join(epicRoot, f));
  const storiesDir = path.join(epicRoot, 'stories');
  const stories = exists(storiesDir)
    ? fs.readdirSync(storiesDir).filter((f) => f.endsWith('.md')).sort().map((f) => path.join(storiesDir, f))
    : [];
  return [...flat, ...stories].filter(exists).sort();
}

// sha256 over the (sorted) artifact files' bytes plus an optional `extra` string (the contract
// surface hash) — the content baseline a site was built from. Deterministic: the file list is
// sorted and each file is length-prefixed so concatenation is unambiguous (a + bc never collides
// with ab + c).
export function docsArtifactHash(files = [], extra = '') {
  const h = createHash('sha256');
  for (const f of [...files].sort()) {
    const buf = fs.readFileSync(f);
    h.update(`${path.basename(f)}:${buf.length}\n`);
    h.update(buf);
  }
  if (extra) h.update(`\ncontract-surface:${extra}`);
  return 'sha256:' + h.digest('hex');
}

// Current HEAD sha per repo the epic touches (mirrors repo.mjs head-sha staleness).
export function repoHeadsFor(root, repos = [], registry = { repos: [] }) {
  const out = {};
  for (const name of repos) {
    const entry = (registry.repos || []).find((r) => r.name === name);
    if (!entry) continue;
    out[name] = gitHead(path.resolve(root, entry.path)) || null;
  }
  return out;
}

// Compare a build manifest to the current world; list the concrete reasons it is stale.
export function docsStale(manifest, { artifactHash, repoHeads = {}, templateVersion } = {}) {
  const reasons = [];
  if (!manifest) return { stale: true, reasons: ['never built'] };
  if (artifactHash && manifest.artifactHash && artifactHash !== manifest.artifactHash) {
    reasons.push('authored artifacts changed');
  }
  for (const [repo, head] of Object.entries(repoHeads)) {
    const was = (manifest.repoHeads || {})[repo];
    if (head && was && head !== was) reasons.push(`repo ${repo} HEAD advanced`);
  }
  if (templateVersion && manifest.templateVersion && templateVersion !== manifest.templateVersion) {
    reasons.push(`doc shell upgraded (${manifest.templateVersion} → ${templateVersion})`);
  }
  return { stale: reasons.length > 0, reasons };
}

// ---- pure: the Pages CI workflow (committed by `yad docs sync --wire`) ---------------------------
// GitHub Actions deploy-pages, or a GitLab `pages` job. Both assemble a single `public/` tree: the
// hand-maintained report.html owns the root (`<base>/` — the main documentation), the overview SPA
// mounts under `app/`, and every per-epic site nests under `epics/<id>/` — matching siteBasePath
// (overview at `<base>/app/`, epics at `<base>/epics/EP-<slug>/`). A concurrency group prevents the
// deploy from retriggering. The shared shell script keeps the two platforms byte-for-byte aligned.
const BUILD_PUBLIC = [
  'mkdir -p public',
  'if [ -d docs/sdlc-site ]; then (cd docs/sdlc-site && npm ci && npm run build) && mkdir -p public/app && cp -r docs/sdlc-site/dist/. public/app/ && cp docs/sdlc-site/public/report.html public/index.html && cp docs/sdlc-site/public/report.html public/report.html; fi',
  'if [ -d docs/tutorial-site ]; then (cd docs/tutorial-site && npm ci && npm run build) && mkdir -p public/tutorial && cp -r docs/tutorial-site/dist/. public/tutorial/; fi',
  'for d in epics/*/docs-site; do [ -d "$d" ] || continue; id=$(basename "$(dirname "$d")"); (cd "$d" && npm ci && npm run build) && mkdir -p "public/epics/$id" && cp -r "$d/dist/." "public/epics/$id/"; done',
];
export function pagesWorkflow(platform) {
  if (platform === 'gitlab') {
    return `# yad-managed — built by \`yad docs sync --wire\`. include it from .gitlab-ci.yml:
#   include: { local: .gitlab/ci/yad-docs.yml }
# Edit the skill, not this file.
pages:
  stage: deploy
  image: node:20
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
${BUILD_PUBLIC.map((l) => `    - '${l.replace(/'/g, "'\\''")}'`).join('\n')}
  artifacts:
    paths: [public]
  resource_group: pages
`;
  }
  return `# yad-managed — built by \`yad docs sync --wire\`. Edit the skill, not this file.
name: yad-docs
on:
  push:
    branches: [main, master]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: yad-docs-pages
  cancel-in-progress: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Build the overview + per-epic sites into ./public
        run: |
${BUILD_PUBLIC.map((l) => `          ${l}`).join('\n')}
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v5
`;
}
export function pagesWorkflowPath(platform) {
  return platform === 'gitlab' ? '.gitlab/ci/yad-docs.yml' : '.github/workflows/yad-docs.yml';
}

// ---- build (subprocess) -------------------------------------------------------------------------
function buildSite(dir) {
  if (!exists(dir)) { warn(`no generated site at ${path.relative(process.cwd(), dir)} — run the yad-docs skill first`); return { ok: false, missing: true }; }
  if (!has('npm')) { warn('npm not on PATH — cannot build; the CI workflow will build on push'); return { ok: false, noNpm: true }; }
  const install = exists(path.join(dir, 'package-lock.json')) ? ['ci'] : ['install'];
  log(`  ${c.dim('$')} npm ${install[0]} ${c.dim(`(${path.relative(process.cwd(), dir)})`)}`);
  const i = run('npm', install, { cwd: dir, stdio: 'inherit' });
  if (!i.ok) { fail('npm install failed'); return { ok: false }; }
  const b = run('npm', ['run', 'build'], { cwd: dir, stdio: 'inherit' });
  if (!b.ok) { fail('npm run build failed'); return { ok: false }; }
  return { ok: true, dist: path.join(dir, 'dist') };
}

// ---- orchestration ------------------------------------------------------------------------------
export async function runDocs(root, { action = 'list', epic, overview, sync } = {}) {
  const { docs } = loadDocs(root);
  const targets = overview ? [{ overview: true }] : epic ? [{ epic }] : enumerateSites(root);

  if (action === 'list') {
    if (!docs) { warn('no docs target connected (.sdlc/docs.json) — run yad-connect-docs'); }
    else {
      log(c.bold('\ndocs target'));
      info(`target ${c.cyan(docs.target)}  scope ${docs.scope}  base ${docs.basePath}  ${docs.source === 'unavailable' ? c.yellow('(build-only)') : ''}`);
    }
    log(c.bold('\ngenerated sites'));
    if (!targets.length) { info('none generated yet'); return { sites: 0 }; }
    for (const t of targets) reportFreshness(root, t);
    return { sites: targets.length };
  }

  if (action === 'build' || action === 'deploy') {
    let built = 0;
    for (const t of targets) {
      const r = buildSite(siteDir(root, t));
      if (r.ok) { built++; ok(`built ${label(t)} ${c.dim('→ ' + path.relative(root, r.dist))}`); }
    }
    if (action === 'deploy') {
      const platform = docs ? (docs.target === 'gitlab-pages' ? 'gitlab' : docs.target === 'github-pages' ? 'github' : null) : null;
      if (!platform || !platformReady(platform)) {
        hand('no Pages platform/CLI — built locally only; commit + push so the CI workflow can publish (yad docs sync --wire)');
      } else {
        ok(`deploy via the ${platform} Pages workflow on push (yad docs sync --wire installs it)`);
        if (docs?.basePath) info(`will publish under ${docs.basePath}`);
      }
    }
    return { built };
  }

  if (action === 'sync') {
    if (sync === 'wire') return wirePages(root, docs);
    // check (default) + refresh both compute staleness; refresh additionally rebuilds.
    const registry = readJSON(path.join(root, PROJECT_FILES.reposRegistry), { repos: [] });
    let stale = 0;
    for (const t of targets) {
      const s = freshness(root, t, registry);
      if (s.stale) {
        stale++;
        warn(`${label(t)} — ${c.yellow('stale')}: ${s.reasons.join('; ')}`);
        if (sync === 'refresh') buildSite(siteDir(root, t));
      } else ok(`${label(t)} ${c.dim('— fresh')}`);
    }
    if (stale && sync !== 'refresh') hand('regenerate content with the yad-docs / yad-docs-overview skill (the AI step), then `yad docs deploy`');
    return { stale };
  }

  fail(`unknown docs action: ${action} (list | build | deploy | sync)`);
  process.exitCode = 1;
  return {};
}

// ---- helpers ------------------------------------------------------------------------------------
function enumerateSites(root) {
  const out = [];
  if (exists(siteDir(root, { overview: true }))) out.push({ overview: true });
  const epicsDir = path.join(root, 'epics');
  if (exists(epicsDir)) {
    for (const e of fs.readdirSync(epicsDir).sort()) {
      if (exists(path.join(epicsDir, e, 'docs-site'))) out.push({ epic: e });
    }
  }
  return out;
}
function label(t) { return t.overview ? 'overview (docs/sdlc-site)' : `epic ${t.epic}`; }

function freshness(root, t, registry) {
  const manifest = readJSON(manifestPath(root, t), null);
  if (t.overview) {
    // The overview is generated from the project pipeline definition, not an epic's artifacts.
    const files = ['skills/sdlc/config.yaml', 'skills/sdlc/module-help.csv', 'docs/diagrams/sdlc-overview.mmd']
      .map((f) => path.join(root, f)).filter(exists);
    return docsStale(manifest, { artifactHash: docsArtifactHash(files), templateVersion: VERSION });
  }
  const epicMeta = readJSON(path.join(root, 'epics', t.epic, '.sdlc/state.json'), {});
  const repos = epicMeta.repos || [];
  const surface = contractSurfaceHash(path.join(root, 'epics', t.epic)); // null when no locked surface
  return docsStale(manifest, {
    artifactHash: docsArtifactHash(docsArtifactFiles(root, t.epic), surface || ''),
    repoHeads: repoHeadsFor(root, repos, registry),
    templateVersion: VERSION,
  });
}
function reportFreshness(root, t) {
  const registry = readJSON(path.join(root, PROJECT_FILES.reposRegistry), { repos: [] });
  const s = freshness(root, t, registry);
  if (s.stale) warn(`${label(t)} — ${c.yellow('stale')}: ${s.reasons.join('; ')}`);
  else ok(`${label(t)} ${c.dim('— fresh')}`);
}

function wirePages(root, docs) {
  const platform = docs?.target === 'gitlab-pages' ? 'gitlab' : 'github';
  const rel = pagesWorkflowPath(platform);
  const dest = path.join(root, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, pagesWorkflow(platform));
  ok(`wired ${rel} ${c.dim(`(${platform} Pages)`)}`);
  if (platform === 'gitlab') hand(`include it from .gitlab-ci.yml:  include: { local: ${rel} }`);
  else hand('commit it; set the repo Pages source to "GitHub Actions" so it publishes on push');
  return { wired: rel };
}
