// `yad repo list|refresh|sync` — connected-repo maintenance as explicit HUMAN decisions.
// list/refresh: staleness of the cached code-context pack (HEAD != syncedHead). Skill steps no longer
// silently repack a stale repo; they flag it and point here. (`yad check --fix` refreshes too — also
// human-invoked.) sync: switch every connected repo to its registry default_branch and fast-forward
// it to origin — a working-tree-only op (it never writes the registry; a dirty tree is skipped).
import path from 'node:path';
import { c, log, ok, info, warn, hand, fail, readJSON, writeJSON, run } from './lib.mjs';
import { PROJECT_FILES } from './manifest.mjs';
import { gitHead, packRepo } from './setup.mjs';
import { publishCodeContext } from './repo-publish.mjs';

function load(root) {
  const regPath = path.join(root, PROJECT_FILES.reposRegistry);
  return { regPath, registry: readJSON(regPath, { repos: [] }) };
}

// HEAD != syncedHead => stale (config.yaml code_context.staleness: head-sha). A repo that has a HEAD but
// no syncedHead was registered without a pack (the greenfield path) — it needs an initial pack, which is
// also a "run `yad repo refresh`" state, kept distinct from HEAD-moved staleness.
function staleness(root, repo) {
  const head = gitHead(path.resolve(root, repo.path));
  const neverPacked = !!head && !repo.syncedHead;
  const stale = head && repo.syncedHead && head !== repo.syncedHead;
  return { head, stale: !!stale, unknown: !head, neverPacked };
}

// ---- git helpers for `sync` (local-user auth only — never embed credentials) ----
const git = (cwd, ...args) => run('git', args, { cwd });
const hasRemote = (cwd, remote = 'origin') => git(cwd, 'remote', 'get-url', remote).ok;
const isDirty = (cwd) => { const r = git(cwd, 'status', '--porcelain'); return r.ok && r.stdout.length > 0; };
const currentBranch = (cwd) => { const r = git(cwd, 'rev-parse', '--abbrev-ref', 'HEAD'); return r.ok ? r.stdout : null; };
// Registry default_branch wins; else origin/HEAD; else 'main'.
function defaultBranch(cwd, repo) {
  if (repo.default_branch) return repo.default_branch;
  const r = git(cwd, 'symbolic-ref', '--short', 'refs/remotes/origin/HEAD');
  return r.ok && r.stdout ? r.stdout.replace(/^origin\//, '') : 'main';
}

export async function runRepo(root, { action = 'list', name, today, push = false, allowBranch = false } = {}) {
  const { regPath, registry } = load(root);
  if (!registry.repos.length) { warn('no repos registered (.sdlc/repos.json) — run `yad setup`'); return { repos: 0 }; }

  if (action === 'list') {
    log(c.bold('\nconnected repos'));
    let staleCount = 0;
    for (const repo of registry.repos) {
      const { stale, unknown, neverPacked } = staleness(root, repo);
      if (unknown) { warn(`${repo.name} ${c.dim(`(${repo.path})`)} — HEAD unreadable`); continue; }
      if (neverPacked) { staleCount++; warn(`${repo.name} ${c.dim(`(${repo.path})`)} — ${c.yellow('no code-context pack yet')} (registered without one)`); }
      else if (stale) { staleCount++; warn(`${repo.name} ${c.dim(`(${repo.path})`)} — ${c.yellow('stale')} (HEAD moved since last pack)`); }
      else ok(`${repo.name} ${c.dim('— fresh')}`);
    }
    if (staleCount) hand(`refresh with \`yad repo refresh${registry.repos.length > 1 ? ' <name>' : ''}\` (or \`yad repo refresh\` for all)`);
    return { repos: registry.repos.length, stale: staleCount };
  }

  if (action === 'refresh') {
    const targets = name ? registry.repos.filter((r) => r.name === name) : registry.repos;
    if (name && !targets.length) { fail(`unknown repo: ${name}`); process.exitCode = 1; return { refreshed: 0 }; }
    let refreshed = 0;
    for (const repo of targets) {
      const { head, unknown } = staleness(root, repo);
      if (unknown) { warn(`${repo.name}: HEAD unreadable — skipped`); continue; }
      log(`  ${c.bold(repo.name)}`);
      if (packRepo(root, repo)) {
        repo.syncedHead = head;
        if (today) repo.lastSyncedAt = today;   // always stamp when a date is supplied (the CLI passes today)
        refreshed++;
      }
    }
    writeJSON(regPath, registry);
    refreshed ? ok(`refreshed ${refreshed} repo(s)`) : info('nothing refreshed');
    if (push) {
      // Publish whatever tracked code-context now differs (the AI-regenerated code-maps + the stamped
      // registry) straight to the hub's default branch as one audit-trail commit. The pack itself is
      // gitignored (packRepo scaffolds the ignore; publish self-heals a pre-ignore tracked pack); the
      // code-map is regenerated by the AI (yad-connect-repos) — run that first if a repo's map is stale,
      // then `yad repo refresh --push` lands it.
      await publishCodeContext(root, { push: true, allowBranch, name });
    } else {
      hand('regenerate the code-map in Claude Code (yad-connect-repos) — the pack is cached, the map is the AI step');
      hand('then publish it to the hub default branch with `yad repo refresh --push`');
    }
    return { refreshed };
  }

  if (action === 'sync') {
    const targets = name ? registry.repos.filter((r) => r.name === name) : registry.repos;
    if (name && !targets.length) { fail(`unknown repo: ${name}`); process.exitCode = 1; return { synced: 0 }; }
    log(c.bold('\nsync connected repos'));
    let synced = 0, skipped = 0;
    for (const repo of targets) {
      const repoRoot = path.resolve(root, repo.path);
      const tag = `${repo.name} ${c.dim(`(${repo.path})`)}`;
      if (!gitHead(repoRoot)) { warn(`${tag} — not a git repo / HEAD unreadable — skipped`); skipped++; continue; }
      if (isDirty(repoRoot)) { warn(`${repo.name} — ${c.yellow('dirty')} → SKIPPED (commit/stash first)`); skipped++; continue; }
      const branch = defaultBranch(repoRoot, repo);
      const remote = hasRemote(repoRoot);
      if (remote) {
        const f = git(repoRoot, 'fetch', 'origin', branch, '--prune');
        if (!f.ok) { warn(`${repo.name} — fetch failed (${(f.stderr.split('\n')[0]) || 'auth?'}) — skipped`); skipped++; continue; }
      }
      if (currentBranch(repoRoot) !== branch) {
        const co = git(repoRoot, 'checkout', branch);
        if (!co.ok) { warn(`${repo.name} — cannot switch to ${branch} (${co.stderr.split('\n')[0] || 'no such branch'}) — skipped`); skipped++; continue; }
      }
      if (remote) {
        const before = gitHead(repoRoot);
        const m = git(repoRoot, 'merge', '--ff-only', `origin/${branch}`);
        if (!m.ok) { warn(`${repo.name} — ${c.yellow('diverged')} on ${branch} → not fast-forwarded (resolve manually)`); skipped++; continue; }
        ok(`${repo.name} ${c.dim('—')} ${before === gitHead(repoRoot) ? `already current on ${branch}` : `switched to ${branch}, pulled (ff)`}`);
      } else {
        ok(`${repo.name} ${c.dim('—')} on ${branch} (local-only, no remote)`);
      }
      synced++;
    }
    // A pulled repo's HEAD moves, so its cached code-context pack goes stale — point the human at refresh.
    const staleCount = registry.repos.filter((r) => staleness(root, r).stale).length;
    info(`synced ${synced}, skipped ${skipped}`);
    if (staleCount) hand(`${staleCount} repo(s) now have a stale code-context pack — \`yad repo refresh\` to repack`);
    return { synced, skipped, stale: staleCount };
  }

  fail(`unknown repo action: ${action} (list | refresh | sync)`);
  process.exitCode = 1;
  return {};
}
