#!/usr/bin/env bash
# verified-commits gate.
# Every commit in the range under review must (1) carry a signature the PLATFORM marks as verified
# (the GitHub/GitLab "Verified" badge — proves the commit was signed by a key registered to the
# account that owns the author email) and (2) be AUTHORED by a known identity: the author email must
# appear in the .sdlc/verified-authors allowlist (generated by `yad check --fix` from the hub
# roster's `email` fields + hub.json `verified_authors`). Unsigned commits and commits from unknown
# authors do not reach merge — on the product hub and on every connected repo alike.
#
# Only the AUTHOR email is checked against the allowlist: platform-generated merge/squash/update
# commits set the platform itself as the committer (e.g. noreply@github.com), and their integrity is
# covered by the signature check (the platform signs them).
#
# Degradation is explicit, never silent:
#   - no allowlist file        -> author check SKIPPED with a warning (configure emails, re-wire)
#   - no GitHub/GitLab remote  -> signature check SKIPPED with a warning (no platform, no badge)
#   - platform API unreachable -> FAIL closed (a security gate must not pass on a broken check)
#
# GitLab note: the signature API is not readable with CI_JOB_TOKEN — provide a CI variable
# GITLAB_TOKEN (or SDLC_API_TOKEN) with read_api scope; see the pipeline fragment header.
set -euo pipefail

BASE="${1:-${SDLC_BASE:-origin/main}}"

# Fail closed if the base ref can't be resolved (shallow clone / wrong base branch / unfetched ref).
if ! git rev-parse --verify --quiet "${BASE}^{commit}" >/dev/null; then
  echo "FAIL [verified-commits]: base ref '${BASE}' not found — fetch full history / check the base branch."
  exit 1
fi
RANGE="${BASE}..HEAD"

commits="$(git rev-list "$RANGE")"
if [ -z "$commits" ]; then
  echo "PASS [verified-commits]: no commits in ${RANGE}"
  exit 0
fi

# ---- author allowlist (one email per line; # comments; case-insensitive) -------------------------
ALLOWLIST="${SDLC_VERIFIED_AUTHORS:-.sdlc/verified-authors}"
authors_on=0
if [ -f "$ALLOWLIST" ]; then
  authors_on=1
else
  echo "WARN [verified-commits]: ${ALLOWLIST} not found — author allowlist NOT enforced. Add 'email' to the hub roster (or hub.json 'verified_authors'), then run \`yad check --fix\`."
fi

# ---- platform for the signature check (override with SDLC_PLATFORM=github|gitlab|none) -----------
remote="$(git remote get-url origin 2>/dev/null || true)"
platform=""
case "$remote" in
  *github*) platform=github ;;
  *gitlab*) platform=gitlab ;;
esac
platform="${SDLC_PLATFORM:-$platform}"
case "$platform" in
  github|gitlab) ;;
  ""|none)
    platform=""
    echo "WARN [verified-commits]: no GitHub/GitLab remote — signature verification SKIPPED (the Verified badge is a platform concept)."
    ;;
  *)
    # Fail closed: an unknown override must never let signature checks silently pass.
    echo "FAIL [verified-commits]: unknown platform '${platform}' (SDLC_PLATFORM must be github|gitlab|none)."
    exit 1
    ;;
esac

# 0 when the platform marks the commit's signature verified.
signature_verified() {
  local sha v body
  sha="$1"
  case "$platform" in
    github)
      v="$(gh api "repos/{owner}/{repo}/commits/${sha}" --jq '.commit.verification.verified' 2>/dev/null || echo api-error)"
      [ "$v" = "true" ]
      ;;
    gitlab)
      # In CI use the documented API directly; locally fall back to the user's own glab.
      if [ -n "${CI_API_V4_URL:-}" ] && [ -n "${CI_PROJECT_ID:-}" ]; then
        body="$(curl -fsS --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-${SDLC_API_TOKEN:-}}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/commits/${sha}/signature" 2>/dev/null || true)"
      else
        body="$(glab api "projects/:id/repository/commits/${sha}/signature" 2>/dev/null || true)"
      fi
      printf '%s' "$body" | grep -qE '"verification_status"[[:space:]]*:[[:space:]]*"verified"'
      ;;
    *) return 1 ;; # unreachable (platform validated above) — keep the gate fail-closed regardless
  esac
}

rc=0
while IFS= read -r sha; do
  [ -z "$sha" ] && continue
  short="$(git log -1 --format=%h "$sha")"
  author="$(git log -1 --format=%ae "$sha" | tr '[:upper:]' '[:lower:]')"

  if [ "$authors_on" = 1 ]; then
    # tolerate CRLF / stray surrounding whitespace in a hand-edited allowlist
    if grep -vE '^[[:space:]]*(#|$)' "$ALLOWLIST" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
        | tr '[:upper:]' '[:lower:]' | grep -qxF "$author"; then
      echo "PASS [verified-commits]: ${short} author <${author}> is a known identity"
    else
      echo "FAIL [verified-commits]: ${short} author <${author}> is not in ${ALLOWLIST} — unverified user."
      rc=1
    fi
  fi

  if [ -n "$platform" ]; then
    if signature_verified "$sha"; then
      echo "PASS [verified-commits]: ${short} signature verified by ${platform}"
    else
      echo "FAIL [verified-commits]: ${short} signature missing/unverified — sign commits (GPG/SSH key registered on ${platform}), or the signature API was unreachable (GitLab: set GITLAB_TOKEN/SDLC_API_TOKEN with read_api)."
      rc=1
    fi
  fi
done <<EOF
$commits
EOF

exit "$rc"
